# SPDX-License-Identifier: GPL-3.0-or-later

include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = ProgrammaticTableViewPlayground
ProgrammaticTableViewPlayground_OBJC_FILES = main.m ApplicationController.m ExampleTableViewController.m

include $(GNUSTEP_MAKEFILES)/application.make